name: pr-build
run-name: ${{ github.actor }} 
on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          go-version: [ '1.19' ]

    steps:
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
      
    # test the matrix by printing the current Go version
    - name: Display Go version
      run: go version
    
    - name: checkout repo
      uses: actions/checkout@main

    - name: build application
      run: make build
  