name: pr-build
run-name: ${{ github.actor }} 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create date of build file
      run: date > pkg/embedded/resources/build-date.txt

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: make
      run: make all
      
  